const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const fs=require('fs'),assert=require('node:assert/strict');const {load}=require('./sdd34-harness.cjs');const d=load('src/shared/journey/domain.ts'),c=load('src/shared/consultation/domain.ts');
const output=process.env.SDD_OUTPUT || 'SDD-Script/evidence/ui-calm';fs.mkdirSync(output,{recursive:true});
const user={id:'00000000-0000-4000-8000-000000000001',email:'fixture@example.invalid',aud:'authenticated',app_metadata:{provider:'email'},user_metadata:{},created_at:'2026-09-01T00:00:00Z'};
let browser;(async()=>{browser=await chromium.launch({channel:'msedge'});let snapshot={revision:0,state:d.emptyJourney(),flags:{triggers:true,coping:true,slips:true,followups:true}},fail=false,closed=true,offline=false,dropMessage=false;const ops=new Map(),checks=[],errors=[];const roomId='00000000-0000-4000-8000-000000000003';let room={user:user.id,consultant:'00000000-0000-4000-8000-000000000002',state:'connected',createdAt:new Date().toISOString(),policy:{version:'fixture'},sharedSummary:'',consentAt:new Date().toISOString(),messages:[],reads:{},reports:[],summary:null,signals:[],operations:{}};
const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.pathname==='/api/journey'){if(req.method()==='GET')return route.fulfill({json:snapshot});const p=req.postDataJSON();if(offline)return route.abort('internetdisconnected');if(fail)return route.fulfill({status:503,json:{error:'Gangguan sintetis'}});if(ops.has(p.operationId))return route.fulfill({json:snapshot});if(p.expectedRevision!==snapshot.revision)return route.fulfill({status:409,json:{error:'Ada perubahan dari perangkat lain.'}});snapshot={...snapshot,revision:snapshot.revision+1,state:d.reduceJourney(snapshot.state,p.action,p.operationId)};ops.set(p.operationId,true);return route.fulfill({json:snapshot});}
if(u.pathname==='/api/consultation')return route.fulfill({json:closed?{available:false,policy:null,consultants:[],rooms:[]}:{available:true,policy:{version:'fixture',cost:'Fixture gratis',boundaries:'Data uji, bukan layanan nyata.',retentionDays:7,waitMinutes:5,hours:[{start:'2026-01-01T00:00:00Z',end:'2027-01-01T00:00:00Z'}]},role:'user',actor:user.id,audio:true,consultants:[],rooms:[{id:roomId}]}});
if(u.pathname==='/api/consultation/'+roomId){if(req.method()==='POST'){const p=req.postDataJSON();room=c.applyRoom(room,user.id,p.action,p.operationId);if(dropMessage && p.action.type==='message'){dropMessage=false;return route.fulfill({status:503,json:{error:'Respons sintetis hilang setelah commit'}});}return route.fulfill({json:{saved:true}});}return route.fulfill({json:{id:roomId,actor:user.id,revision:1,previous:null,document:room}});}
if(u.hostname==='127.0.0.1')return route.continue();if(u.pathname==='/auth/v1/user')return route.fulfill({json:user});if(u.pathname.startsWith('/rest/v1/'))return route.fulfill({json:(req.headers().accept||'').includes('vnd.pgrst.object')?null:[]});return route.abort();});
await context.addInitScript(({user})=>{const token=btoa(JSON.stringify({alg:'HS256',typ:'JWT'}))+'.'+btoa(JSON.stringify({sub:user.id,exp:9999999999,aud:'authenticated'}))+'.fixture';localStorage.setItem('supabase.auth.token',JSON.stringify({access_token:token,refresh_token:'fixture',expires_at:9999999999,expires_in:3600,token_type:'bearer',user}));localStorage.setItem('userToken',token);localStorage.setItem('userId',user.id);localStorage.setItem('lastLoginAt',String(Date.now()));Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:()=>Promise.reject(new DOMException('Fixture denied','NotAllowedError'))});},{user});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));async function go(path){await page.goto('http://127.0.0.1:3000/'+path,{waitUntil:'networkidle',timeout:120000});}async function saved(){await page.getByText('Tersimpan di server.',{exact:true}).waitFor();}
let profileFails=true;
await page.route('**/api/profile', async route => {
  if (route.request().method() === 'GET') return route.fulfill({ json: { profile: { full_name: 'Profil Uji', email: user.email, phone_number: '', gender: '', date_of_birth: null, motivations: [] } } });
  const payload = route.request().postDataJSON();
  assert.equal(payload.full_name, 'Profil Baru');
  assert.equal('user_id' in payload || 'email' in payload, false);
  return route.fulfill({ status: profileFails ? 503 : 200, json: profileFails ? { error: 'Perubahan belum tersimpan. Silakan coba lagi.' } : { success: true } });
});
await go('profile-settings');
await page.getByLabel('Nama Lengkap', { exact: true }).fill('Profil Baru');
await page.getByRole('button', { name: 'Simpan Perubahan' }).click();
await page.getByText('Perubahan belum tersimpan. Silakan coba lagi.', { exact: true }).waitFor();
assert.equal(await page.getByLabel('Nama Lengkap', { exact: true }).inputValue(), 'Profil Baru');
assert.equal(await page.getByText('Perubahan profil tersimpan.', { exact: true }).count(), 0);
assert.equal(await page.getByLabel('Email', { exact: true }).getAttribute('readonly'), '');
profileFails=false;
await page.getByRole('button', { name: 'Simpan Perubahan' }).click();
await page.getByText('Perubahan profil tersimpan.', { exact: true }).waitFor();
await page.screenshot({ path: output+'/profile-save.png', fullPage: true });
checks.push('Profile uses authenticated API, preserves failed edits, and reports only confirmed saves.');
let motivationAttempts=0;
await page.route('**/api/profile/motivations', async route => {
  assert.deepEqual(route.request().postDataJSON(), { motivations: ['Kesehatan'] });
  assert.match(route.request().headers().authorization, /^Bearer /);
  motivationAttempts++;
  await route.fulfill({ status: motivationAttempts === 1 ? 503 : 200, json: motivationAttempts === 1 ? { error: 'Fixture unavailable' } : { success: true } });
});
await go('motivation');
await page.getByLabel('Kesehatan', { exact: true }).check();
await page.getByRole('button', { name: 'Simpan dan buka Home' }).click();
await page.getByText('Pilihan belum tersimpan. Silakan coba lagi.', { exact: true }).waitFor();
assert.equal(await page.getByLabel('Kesehatan', { exact: true }).isChecked(), true);
await page.getByRole('button', { name: 'Simpan dan buka Home' }).click();
await page.waitForURL('**/home');
assert.equal(motivationAttempts, 2);
checks.push('Motivation uses authenticated API, preserves selection on failure, and retries.');
await go('home');await page.getByLabel('Jumlah batang (0').fill('0');await page.getByRole('button',{name:'Simpan catatan',exact:true}).click();await saved();assert.equal(Object.values(snapshot.state.daily)[0].count,0);checks.push('Zero saved as reported.');
fail=true;await page.getByLabel('Jumlah batang (0').fill('3');await page.getByRole('button',{name:'Simpan catatan',exact:true}).click();await page.getByText('Ada isian yang belum tersinkron',{exact:true}).waitFor();assert.equal(Object.values(snapshot.state.daily)[0].count,0);checks.push('Failed save retains pending operation, no false success.');
fail=false;snapshot.revision++;await page.getByRole('button',{name:'Kirim ulang',exact:true}).click();await page.getByRole('alert').filter({hasText:'perangkat lain'}).waitFor();await page.getByText('Pilihan jika ada perubahan dari perangkat lain',{exact:true}).click();await page.getByRole('button',{name:'Terapkan isian ini pada versi terbaru'}).click();await saved();assert.equal(Object.values(snapshot.state.daily)[0].count,3);checks.push('Two-device conflict requires explicit apply; retry updates one record.');
offline=true;await context.setOffline(true);await page.getByLabel('Jumlah batang (0').fill('4');await page.getByRole('button',{name:'Simpan catatan',exact:true}).click();await page.getByText('Ada isian yang belum tersinkron',{exact:true}).waitFor();offline=false;await context.setOffline(false);await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'Kirim ulang',exact:true}).click();await saved();assert.equal(Object.values(snapshot.state.daily)[0].count,4);checks.push('Offline operation survives reload and syncs when explicitly retried.');
await go('tracker');await page.getByRole('table').waitFor();assert.equal(await page.getByRole('cell',{name:'Belum tercatat',exact:true}).count(),6);checks.push('Tracker preserves six missing days.');
await page.route('**/api/journey/legacy?*', route => route.fulfill({ json: { records: [{ id: 'legacy-fixture', date: '2026-01-01', cigarette_count: 0, money_spent: 0 }], nextOffset: null } }));
await page.getByRole('button', { name: 'Lihat catatan terdahulu' }).click();
await page.getByRole('table', { name: 'Riwayat konsumsi terdahulu' }).waitFor();
assert.equal(await page.getByRole('table', { name: 'Riwayat konsumsi terdahulu' }).getByRole('cell', { name: '0', exact: true }).count(), 1);
checks.push('Legacy consumption remains readable; reported zero is preserved without migration guesses.');
await go('craving-support');await page.getByLabel('Apa pemicunya?').fill('Setelah makan');await page.getByRole('button',{name:'Simpan check-in'}).click();await saved();assert.equal(snapshot.state.checkins.length,1);
await page.getByLabel('Konteks (opsional)').fill('Draft tetap ada');await page.getByRole('tab',{name:'Check-in',exact:true}).focus();await page.keyboard.press('ArrowRight');assert.equal(await page.getByRole('tab',{name:'Langkah saya',exact:true}).getAttribute('aria-selected'),'true');await page.keyboard.press('ArrowLeft');assert.equal(await page.getByLabel('Konteks (opsional)').inputValue(),'Draft tetap ada');checks.push('Keyboard tabs change panels and preserve unsaved input.');
await page.getByRole('tab',{name:'Langkah saya',exact:true}).click();await page.getByLabel('Jika pemicu ini muncul').fill('Setelah makan');await page.getByLabel('Langkah pilihan pertama').fill('Langkah pilihan satu');await page.getByLabel('Langkah kedua',{exact:true}).fill('Langkah pilihan dua');await page.getByRole('button',{name:'Simpan langkah saya'}).click();await saved();await page.getByLabel('Gunakan rencana').selectOption(snapshot.state.coping[0].id);await page.getByText('Langkah 1: Langkah pilihan satu',{exact:true}).waitFor();await page.getByRole('button',{name:'Langkah berikutnya'}).click();await page.getByText('Langkah 2: Langkah pilihan dua',{exact:true}).waitFor();checks.push('Trigger check-in and user-authored coping work.');
await page.getByRole('tab',{name:'Saya merokok lagi',exact:true}).click();await page.getByLabel('Waktu kejadian').fill('2026-09-01T10:00');await page.getByLabel('Langkah yang saya pilih berikutnya').fill('Gunakan rencana saya');await page.getByRole('button',{name:'Simpan kejadian'}).click();await saved();assert.equal(snapshot.state.slips.length,1);checks.push('Slip form saves without phase reset.');
await go('pencapaian');await page.getByRole('tab',{name:'Pengingat',exact:true}).click();await page.getByLabel('Aktifkan pengingat').check();await page.getByLabel('Saya setuju menerima').check();await page.getByLabel('Tindak lanjut hari').fill('1,7,30');await page.getByRole('button',{name:'Simpan pilihan pengingat'}).click();await saved();assert.deepEqual(snapshot.state.preferences.followupDays,[1,7,30]);await page.getByLabel('Aktifkan pengingat').uncheck();await page.getByRole('button',{name:'Simpan pilihan pengingat'}).click();await saved();assert.equal(snapshot.state.preferences.enabled,false);checks.push('Reminder consent, schedule and disable save.');
for(const width of [320,390,768,1024,1440]){
  await page.setViewportSize({width,height:900});
  for(const route of ['welcome','home','tracker','pencapaian','craving-support','contact-professional']){
    await go(route);
    if(['home','tracker','pencapaian','craving-support'].includes(route))await page.locator('.nivo-data-note').waitFor();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' overflow '+width);
    const logo=page.getByRole('img',{name:'NIVO',exact:true}).first();
    await logo.evaluate(img=>img.decode());
    assert.equal(await logo.evaluate(img=>img.complete && img.naturalWidth>0),true,'Original logo loaded');
    await page.screenshot({path:output+'/'+route+'-'+width+'.png',fullPage:true});
  }
}
checks.push('30 page/viewport combinations have no horizontal overflow and original logo loads.');
await page.setViewportSize({width:390,height:844});await go('pencapaian');await page.evaluate(()=>document.documentElement.style.fontSize='200%');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'200% font overflow');await page.screenshot({path:output+'/journey-font-200.png',fullPage:true});await page.evaluate(()=>document.documentElement.style.fontSize='');
await page.getByRole('button',{name:'Buka menu akun'}).click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Buka menu akun');checks.push('200% root font avoids overflow; account menu Escape restores focus.');
closed=false;await page.setViewportSize({width:320,height:750});await go('contact-professional');await page.getByRole('button',{name:'Buka sesi'}).click();await page.getByText('Sesi chat aktif',{exact:true}).waitFor();await page.getByLabel('Pesan',{exact:true}).fill('Pesan sintetis');dropMessage=true;await page.getByRole('button',{name:'Kirim pesan',exact:true}).click();await page.getByRole('button',{name:'Kirim ulang pesan yang sama'}).click();await page.getByText('Pesan sintetis',{exact:true}).waitFor();assert.equal(room.messages.length,1);await page.getByRole('button',{name:'Panggil dan izinkan mikrofon'}).click();await page.getByText('Izin mikrofon ditolak. Kamu tetap bisa menggunakan chat.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'active chat overflow');await page.screenshot({path:output+'/chat-microphone-denied.png',fullPage:true});checks.push('Chat sends and microphone denial preserves fallback chat.');
let otpVerifications=0,passwordUpdates=0;
const fixtureToken=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:user.id,exp:9999999999,aud:'authenticated'})).toString('base64url')+'.fixture';
let loginAttempts=0;
await page.route('**/auth/v1/token?grant_type=password',async route => {
  loginAttempts++;
  await route.fulfill({status:loginAttempts===1?400:200,json:loginAttempts===1?{code:'invalid_credentials',msg:'Invalid login credentials'}:{access_token:fixtureToken,refresh_token:'fixture',expires_in:3600,token_type:'bearer',user}});
});
await go('signin');
await page.getByLabel('Email',{exact:true}).fill(user.email);
await page.getByLabel('Password',{exact:true}).fill('Synthetic-password');
await page.getByRole('button',{name:'Sign In',exact:true}).click();
await page.getByText('Invalid login credentials',{exact:true}).waitFor();
assert.equal(await page.getByLabel('Email',{exact:true}).inputValue(),user.email);
await page.getByRole('button',{name:'Sign In',exact:true}).click();
await page.waitForURL('**/home');
assert.equal(loginAttempts,2);
checks.push('Password sign-in retains failed input and opens Home only after successful response.');
await page.route('**/auth/v1/signup*',route=>route.fulfill({json:{user,session:null}}));
await go('signup');
await page.getByLabel('Email',{exact:true}).fill(user.email);
await page.getByLabel('Password',{exact:true}).fill('Synthetic-password');
await page.getByRole('button',{name:'Sign Up',exact:true}).click();
await page.getByRole('heading',{name:'Akun Berhasil Dibuat!',exact:true}).waitFor();
checks.push('Signup without a session requests email verification before entering the app.');
await page.route('**/auth/v1/verify', async route => {
  otpVerifications++;
  assert.equal(route.request().postDataJSON().type,'recovery');
  await route.fulfill({ json: { access_token:fixtureToken,refresh_token:'fixture',expires_in:3600,token_type:'bearer',user } });
});
await page.route('**/auth/v1/user', async route => {
  if(route.request().method() !== 'PUT') return route.fallback();
  passwordUpdates++;
  assert.equal(route.request().postDataJSON().password,'Synthetic-password');
  await route.fulfill({json:user});
});
await page.evaluate(() => localStorage.setItem('resetEmail','fixture@example.invalid'));
await go('otp-verification');
await page.locator('input[autocomplete="one-time-code"]').fill('123456');
await page.getByRole('button',{name:'Verifikasi',exact:true}).click();
await page.waitForURL('**/reset-password');
await page.getByLabel('Password Baru',{exact:true}).fill('Synthetic-password');
await page.getByLabel('Konfirmasi Password',{exact:true}).fill('Synthetic-password');
await page.getByRole('button',{name:'Update Password',exact:true}).click();
await page.waitForURL('**/password-reset-success');
assert.equal(otpVerifications,1);assert.equal(passwordUpdates,1);
checks.push('OTP recovery verifies once and updates password only on final submit.');
const authOutage=route => route.fulfill({status:503,json:{code:'unexpected_failure',msg:'Fixture unavailable'}});
await page.route('**/auth/v1/user',authOutage);
await page.evaluate(userId => localStorage.setItem('nivo.pending.'+userId,'fixture-preserved'),user.id);
await go('home');
await page.getByText('Sesi belum dapat diverifikasi. Isian sementara tetap tersimpan; coba lagi saat koneksi tersedia.',{exact:true}).waitFor();
assert.equal(await page.evaluate(userId => localStorage.getItem('nivo.pending.'+userId),user.id),'fixture-preserved');
await page.unroute('**/auth/v1/user',authOutage);
checks.push('Auth outage preserves pending drafts and does not falsely log out the user.');
assert.deepEqual(errors,[]);fs.writeFileSync(output+'/browser-results.json',JSON.stringify({checks,errors},null,2));await browser.close();console.log(checks.join('\n'));})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
