'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { PageTitle, Panel, StateNotice, ActionLink } from '@/components/ui/nivo';
import { authenticatedRequest } from '@/shared/journey/client';
import { Policy, Room, RoomAction } from '@/shared/consultation/domain';
import { useAudio } from '@/shared/consultation/useAudio';
import { AudioLines, ArrowUpRight, MessageCircle, ShieldCheck } from 'lucide-react';
type Directory = { available: boolean; policy: Policy | null; actor?: string; role?: string; audio?: boolean; rooms: { id: string }[]; consultants: { id: string; name: string; credentials: string; available: boolean }[] };
export default function ContactProfessionalPage() {
  const [directory, setDirectory] = useState<Directory | null>(null), [id, setId] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const attempt = useRef<object | null>(null), lock = useRef(false);
  const load = useCallback(async () => { try { setDirectory(await authenticatedRequest('/api/consultation')); setError(''); } catch (e) { setError(e.message); } }, []);
  useEffect(() => { load(); }, [load]);
  return <div className="nivo-page"><PageTitle eyebrow="Ada ruang untuk bercerita" title="Konsultasi di NIVO">Pilih dukungan manusia saat kamu membutuhkannya.</PageTitle>
    {error && <StateNotice error>{error}</StateNotice>}
    {id ? <Session key={id} id={id} audioEnabled={!!directory?.audio} onBack={() => { setId(''); load(); }} /> : <>
    {!directory?.policy ? <>
      <section className="nivo-empty-service"><span className="nivo-status-orb" aria-hidden="true"><MessageCircle size={28} strokeWidth={1.5} /></span><div><p className="nivo-eyebrow">Dukungan manusia</p><h2>{error ? 'Ketersediaan belum dapat dimuat' : directory ? 'Layanan belum tersedia' : 'Memeriksa ketersediaan…'}</h2></div><p>{error ? 'Periksa koneksi lalu coba kembali untuk melihat layanan konsultasi.' : directory ? 'Belum ada jadwal atau konsultan terverifikasi yang dapat ditampilkan. Kamu belum masuk antrean.' : 'Sebentar, kami sedang memuat informasi layanan.'}</p><div className="nivo-button-row"><button className="nivo-action" onClick={load}>Periksa ketersediaan <ArrowUpRight size={17} aria-hidden="true" /></button><ActionLink href="/craving-support" secondary>Bantuan mandiri</ActionLink></div></section>
      <div className="nivo-dashboard-grid"><Panel title="Chat atau suara, sesuai pilihanmu" tone="plain"><div className="nivo-calm-intro"><AudioLines size={22} aria-hidden="true" /><p>Saat layanan tersedia, kamu bisa melihat jadwal dan biaya sebelum memulai.</p></div><p className="nivo-caption">Konsultasi bersifat opsional. Kamu tetap dapat mencatat dan menggunakan langkah bantuan mandiri.</p></Panel><Panel title="Kamu menentukan yang dibagikan" tone="plain"><ShieldCheck size={24} strokeWidth={1.5} aria-hidden="true" /><p className="nivo-caption">Ringkasan perjalanan hanya dibagikan jika kamu memilihnya. Panduan otomatis dan percakapan dengan manusia ditampilkan secara terpisah.</p></Panel></div>
    </> : <>
    <Panel title="Jadwal, biaya, dan batas layanan"><p>{directory.available ? 'Dalam jam layanan. Ketersediaan setiap konsultan dapat berubah.' : 'Di luar jam layanan; belum menerima antrean baru.'}</p><p>Zona waktu perangkat: {Intl.DateTimeFormat().resolvedOptions().timeZone}</p>{directory.policy.hours.map(h => <p key={h.start}>{new Date(h.start).toLocaleString('id-ID')} – {new Date(h.end).toLocaleString('id-ID')}</p>)}<p>Biaya: {directory.policy.cost}. Perkiraan tunggu: {directory.policy.waitMinutes} menit (bukan jaminan).</p><p>{directory.policy.boundaries}</p><p>Chat disimpan {directory.policy.retentionDays} hari sejak sesi dibuat. Audio tidak direkam. Audit akses disimpan 30 hari. Lampiran tidak didukung.</p></Panel>
    {directory.role === 'user' && <Panel title="Pilih konsultan manusia"><form className="nivo-stack" onSubmit={async e => { e.preventDefault(); if (lock.current) return; lock.current = true; setBusy(true); setError(''); const f = new FormData(e.currentTarget); try { if (!attempt.current) attempt.current = { id: crypto.randomUUID(), consultant: f.get('consultant'), consent: f.has('consent'), policyVersion: directory.policy.version, sharedSummary: f.has('share') ? String(f.get('summary') || '') : '' }; const result = await authenticatedRequest('/api/consultation', { method: 'POST', body: JSON.stringify(attempt.current) }); setId(result.id); attempt.current = null; } catch (e) { setError(e.message + ' Coba lagi untuk mengirim isian yang sama.'); } finally { lock.current = false; setBusy(false); } }}><fieldset disabled={busy || !!attempt.current} className="nivo-stack"><label>Konsultan<select name="consultant" required className="block border p-3 w-full"><option value="">Pilih yang tersedia</option>{directory.consultants.map(c => <option key={c.id} value={c.id} disabled={!c.available}>{c.name} — {c.credentials} ({c.available ? 'tersedia' : 'tidak tersedia'})</option>)}</select></label><label><input name="consent" type="checkbox" required /> Saya menyetujui batas layanan dan retensi di atas (versi {directory.policy.version})</label><label><input name="share" type="checkbox" /> Saya ingin membagikan ringkasan yang saya tulis (opsional)</label><label>Ringkasan pilihanmu<textarea name="summary" maxLength={2000} className="block border p-3 w-full" /></label><p>Menolak berbagi ringkasan tidak menghalangi konsultasi. Data perjalanan tidak dikirim otomatis.</p></fieldset><button className="nivo-action" disabled={busy || !directory.available}>Mulai antrean chat</button></form></Panel>}
    {directory.role === 'admin' && <Moderation />}
    <Panel title="Sesi saya">{directory.rooms.length ? directory.rooms.map(r => <button key={r.id} className="nivo-action nivo-action-secondary" onClick={() => setId(r.id)}>Buka sesi {r.id.slice(0, 8)}</button>) : <p>Belum ada sesi.</p>}<button className="nivo-action" onClick={load}>Muat ulang sesi</button></Panel></>}
    </>}
    <p className="nivo-caption nivo-divider">NIVO bukan layanan darurat. Jika membutuhkan bantuan segera, hubungi fasilitas kesehatan yang kamu kenal.</p>
  </div>;
}
function Session({ id, audioEnabled, onBack }: { id: string; audioEnabled: boolean; onBack: () => void }) {
  const [room, setRoom] = useState<Room | null>(null), [actor, setActor] = useState(''), [error, setError] = useState(''), [online, setOnline] = useState(true), [draft, setDraft] = useState(''), [pending, setPending] = useState<{ operationId: string; action: RoomAction } | null>(null), [busy, setBusy] = useState(false), [previous, setPrevious] = useState<number | null>(null), [older, setOlder] = useState<Room['messages']>([]), [confirmation, setConfirmation] = useState('');
  const lock = useRef(false), lastRead = useRef(''), latest = useRef<Room | null>(null), pageCursor = useRef<number | null>(null);
  const load = useCallback(async () => { try { const data = await authenticatedRequest('/api/consultation/' + id); setRoom(data.document); latest.current = data.document; setActor(data.actor); if (pageCursor.current === null) setPrevious(data.previous); setOnline(true); } catch (e) { setOnline(false); setError(e.message); } }, [id]);
  const send = useCallback(async (action: RoomAction) => { await authenticatedRequest('/api/consultation/' + id, { method: 'POST', body: JSON.stringify({ operationId: crypto.randomUUID(), action }) }); }, [id]);
  useEffect(() => { let disposed = false; let timer: ReturnType<typeof setTimeout>; const poll = async () => { await load(); if (!disposed) timer = setTimeout(poll, 3000); }; poll(); const pulse = setInterval(() => { if (latest.current?.state !== 'ended') send({ type: 'heartbeat' }).catch(() => {}); }, 15000); return () => { disposed = true; clearTimeout(timer); clearInterval(pulse); }; }, [load, send]);
  useEffect(() => { if (!room || !actor || document.visibilityState !== 'visible') return; const last = room.messages.at(-1); if (last && last.sender !== actor && last.id !== lastRead.current) { lastRead.current = last.id; send({ type: 'read', messageId: last.id }).catch(() => { lastRead.current = ''; }); } }, [room, actor, send]);
  const audio = useAudio(id, room, actor, send);
  const act = async (action: RoomAction) => { try { await send(action); setError(''); await load(); } catch (e) { setError(e.message); } };
  const submitMessage = async () => { if (lock.current || (!draft.trim() && !pending)) return; lock.current = true; setBusy(true); const operation = pending || { operationId: crypto.randomUUID(), action: { type: 'message', text: draft } as RoomAction }; setPending(operation); try { await authenticatedRequest('/api/consultation/' + id, { method: 'POST', body: JSON.stringify(operation) }); setPending(null); setDraft(''); setError(''); await load(); } catch (e) { setError(e.message + ' Pesan belum dikonfirmasi; coba kirim ulang.'); } finally { lock.current = false; setBusy(false); } };
  const peer = room && (actor === room.user ? room.consultant : room.user), seen = room?.lastSeen?.[peer];
  return <div className="nivo-stack"><button className="nivo-action nivo-action-secondary" onClick={() => { audio.end(); onBack(); }}>Kembali ke daftar sesi</button>{error && <StateNotice error>{error}</StateNotice>}{!online && <StateNotice error>Koneksi terputus. Pesan belum tentu terkirim. Chat yang sudah dimuat tetap bisa dibaca.</StateNotice>}
    {!room ? <StateNotice>Memuat sesi…</StateNotice> : <>
    <Panel tone="soft" eyebrow="Status percakapan" title={room.state === 'queued' ? 'Menunggu konsultan menerima sesi' : room.state === 'connected' ? 'Sesi chat aktif' : 'Sesi berakhir'}><p className="nivo-caption">{seen && Date.now() - Date.parse(seen) < 45000 ? 'Lawan bicara baru saja aktif.' : 'Kehadiran lawan bicara belum terkonfirmasi; mereka mungkin offline atau menutup tab.'}</p>{room.sharedSummary && <p>Ringkasan yang dibagikan: {room.sharedSummary}</p>}{room.state === 'queued' && actor === room.consultant && <button className="nivo-action" onClick={() => act({ type: 'accept' })}>Terima sesi</button>}{room.state !== 'ended' && <div className="nivo-button-row"><button className="nivo-action nivo-action-secondary" onClick={() => { audio.end(); act({ type: 'end' }); }}>Akhiri sesi</button></div>}</Panel>
    <Panel title="Chat dengan manusia">{previous != null && <button className="nivo-action nivo-action-secondary" onClick={async () => { try { const data = await authenticatedRequest('/api/consultation/' + id + '?before=' + previous); setOlder(prev => [...data.document.messages, ...prev]); pageCursor.current = data.previous || 0; setPrevious(data.previous); } catch (e) { setError(e.message); } }}>Muat pesan sebelumnya</button>}<div className="nivo-chat-log" aria-label="Pesan percakapan" tabIndex={0}>{!room.messages.length && !older.length && <div className="nivo-chat-empty"><MessageCircle size={26} className="mx-auto" aria-hidden="true" /><p>Belum ada pesan.</p><p className="nivo-caption">{room.state === 'connected' ? 'Mulai dari hal yang ingin kamu ceritakan.' : 'Pesan akan tampil di sini setelah percakapan dimulai.'}</p></div>}{[...new Map([...older, ...room.messages].map(m => [m.id, m])).values()].map(m => <div key={m.id} className={`nivo-chat-bubble ${m.sender === actor ? 'nivo-chat-bubble-own' : ''}`}><p className="nivo-chat-author">{m.sender === actor ? 'Saya' : m.sender === room.consultant ? 'Konsultan manusia' : 'Pengguna'}</p><p className="whitespace-pre-wrap">{m.text}</p><small>{new Date(m.at).toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })} · Tersimpan di server{room.reads[peer] === m.id ? ' · Dibaca' : ''}</small></div>)}</div>{room.state === 'connected' && <form className="nivo-chat-composer" onSubmit={e => { e.preventDefault(); submitMessage(); }}><label>Pesan<textarea maxLength={2000} value={draft} disabled={!!pending} onChange={e => setDraft(e.target.value)} placeholder="Tulis yang ingin kamu ceritakan…" /></label><button className="nivo-action" disabled={busy}>{busy ? 'Mengirim…' : pending ? 'Kirim ulang pesan yang sama' : 'Kirim pesan'}<ArrowUpRight size={17} aria-hidden="true" /></button></form>}<p className="nivo-caption">Hanya teks. Isian pesan yang belum terkirim hilang jika tab ditutup.</p></Panel>
    {audioEnabled && room.state === 'connected' && <Panel title="Panggilan suara browser"><p role="status">{audio.status}</p><audio className="w-full max-w-full" ref={audio.audio} controls autoPlay aria-label="Audio lawan bicara" />{audio.active ? <><button className="nivo-action" onClick={audio.toggleMute}>{audio.muted ? 'Aktifkan mikrofon' : 'Mute mikrofon'}</button><button className="nivo-action nivo-action-secondary" onClick={audio.end}>Akhiri panggilan</button></> : <button className="nivo-action" onClick={() => audio.start(audio.incoming)}>{audio.incoming ? 'Jawab panggilan dan izinkan mikrofon' : 'Panggil dan izinkan mikrofon'}</button>}<p>Audio tidak direkam. Kamu dapat menolak izin mikrofon dan melanjutkan chat.</p></Panel>}
    <Panel title="Ringkasan tindakan">{room.summary ? <><p>{room.summary.text}</p><p>{room.summary.approved ? 'Disetujui pengguna.' : 'Usulan konsultan; belum disetujui pengguna.'}</p>{actor === room.user && !room.summary.approved && <button className="nivo-action" onClick={() => act({ type: 'approve_summary' })}>Saya menyetujui ringkasan ini</button>}</> : <p>Belum ada ringkasan yang diajukan.</p>}{actor === room.consultant && room.state === 'connected' && <form onSubmit={e => { e.preventDefault(); act({ type: 'summary', text: String(new FormData(e.currentTarget).get('summary')) }); }}><label>Usulan tindakan<textarea name="summary" className="block w-full border p-3" required maxLength={2000} /></label><button className="nivo-action">Ajukan ringkasan</button></form>}</Panel>
    <Panel title="Penilaian opsional"><p>Seberapa puas kamu dengan sesi ini? 1 sangat tidak puas, 5 sangat puas.</p><div className="flex flex-wrap gap-2">{[1,2,3,4,5].map(score => <button key={score} className="nivo-action nivo-action-secondary" aria-pressed={room.satisfaction?.[actor] === score} onClick={() => act({ type: 'satisfaction', score })}>{score}</button>)}</div><p>Penilaian boleh dilewati. Data teknis yang dicatat hanya jumlah kejadian koneksi, tanpa isi audio.</p></Panel>
    <Panel title="Laporkan dan kelola sesi"><form onSubmit={e => { e.preventDefault(); act({ type: 'report', reason: String(new FormData(e.currentTarget).get('reason')) }); }}><label>Alasan laporan<textarea name="reason" className="block w-full border p-3" required maxLength={500} /></label><button className="nivo-action nivo-action-secondary">Kirim laporan ke admin</button></form><p>{room.reports.length} laporanmu tercatat.</p>{actor === room.user && room.state === 'ended' && <><label>Ketik HAPUS CHAT untuk menghapus isi sesi<input className="block border p-3" value={confirmation} onChange={e => setConfirmation(e.target.value)} /></label><button className="nivo-action nivo-action-secondary" disabled={confirmation !== 'HAPUS CHAT'} onClick={async () => { try { await authenticatedRequest('/api/consultation/' + id, { method: 'DELETE', body: JSON.stringify({ confirm: confirmation }) }); setOlder([]); setConfirmation(''); await load(); } catch (e) { setError(e.message); } }}>Hapus isi chat</button></>}</Panel>
    </>}
  </div>;
}

function Moderation() {
  const [reports, setReports] = useState<{ id: string; state: string; reports: { id: string; reason: string }[] }[]>([]), [error, setError] = useState(''), [next, setNext] = useState<number | null>(0);
  const load = async () => { try { const result = await authenticatedRequest('/api/consultation/admin?offset=' + (next || 0)); setReports(old => [...old, ...result.reports]); setNext(result.next); } catch (e) { setError(e.message); } };
  return <Panel title="Moderasi administratif"><p>Akses laporan dicatat dalam audit. Muat halaman berikutnya untuk melanjutkan peninjauan.</p>{error && <StateNotice error>{error}</StateNotice>}{reports.map(r => <div className="nivo-stack border p-3" key={r.id}><p>Sesi {r.id.slice(0, 8)}: {r.state}</p>{r.reports.map(report => <p key={report.id}>{report.reason}</p>)}<form onSubmit={async e => { e.preventDefault(); try { await authenticatedRequest('/api/consultation/admin', { method: 'POST', body: JSON.stringify({ id: r.id, reason: String(new FormData(e.currentTarget).get('reason')) }) }); setReports(old => old.map(x => x.id === r.id ? { ...x, state: 'ended' } : x)); } catch (e) { setError(e.message); } }}><label>Alasan penghentian<input className="block border p-3 w-full" name="reason" maxLength={500} required /></label><button className="nivo-action" disabled={r.state === 'ended'}>Hentikan sesi</button></form></div>)}{next !== null && <button className="nivo-action" onClick={load}>Muat laporan berikutnya</button>}</Panel>;
}
